<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBmeQrRK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBmeQrRK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBmeQrRK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBmeQrRK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBmeQrRK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BmeQrRK',
    'container.build_id' => '693bd4d1',
    'container.build_time' => 1598439016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBmeQrRK');
